config/routes.rb
Vocabulator::Application.routes.draw do
  resources :users
  resources :attempts,      only: [:new, :create, :destroy]
  resources :sessions,      only: [:new, :create, :destroy]
  root to: 'static_pages#home'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  scope :jacob, as: 'jacob' do
    match '/about',      to: 'static_pages#jacob',       via: 'get'
    match '/coursework', to: 'static_pages#coursework',  via: 'get'
  end

  scope :dungeons_and_dragons, as: 'dungeons_and_dragons' do
    match '/home', to: 'd_and_d#home', via: 'get'
    match '/file', to: 'd_and_d#file', via: 'get'
    match '/dm', to: 'd_and_d#dm', via: 'get'
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if signed_in?
      @attempts = current_user.attempts
    end
  end

  def about
  end

  def contact
  end

  def jacob
  end

  def coursework
    @fall_2006 = Course::FALL_2006
    @spring_2007 = Course::SPRING_2007
    #@fall_2007 = Course::FALL_2007
    #@spring_2008 = Course::SPRING_2008
    #@fall_2008 = Course::FALL_2008
    #@spring_2009 = Course::SPRING_2009
    #@fall_2009 = Course::FALL_2009
    #@spring_2010 = Course::SPRING_2010
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_semester.html.haml
.semester_wrapper
  .semester
    %p= season
    %p= year
  %table.classes
    %thead
      %tr
        %th Course
        %th Area
        %th Grade
        %th Work
    %tbody
      - courses.each do |c|
        %tr
          %td= c[:name]
          %td= c[:area]
          %td= c[:grade]
          %td= c[:work]

app/views/static_pages/about.html.haml
- provide(:title, 'About Us')
%h1 Mastering the 500 most common SAT words has never been easier!
%p
  Vocabulator is a online application allowing you to practice the most common SAT words from the cloud.  After creating an account, you may log in from anywhere ad continue right where you left off!
%p
  Beyond that, Vocabulator is designed to maximize your learning in the shortest amount of time;
%ul
  %li We choose the most common words
  %li (coming soon) The library of words are divided into 'chunks'.  Once you have mastered enough of a chunk, we move onto the next section while remembering words you haven't quite mastered from previous chunks.
  %li We choose questions intelligently.  Our algorithms asure that you never waste time on a question you have mastered (except for special review sections)
  %li (coming soon) We crowd-source the most helpful user suggested example sentences, quotes and pop cultural references to help you associate words with real life examples.

app/views/static_pages/contact.html.haml
- provide(:title, 'Contact')
%h1 Contact
%p
  Contact me

app/views/static_pages/coursework.html.haml
- provide(:title, 'Jacob Dankner')
%h1 CourseWork
.row.miami
  .span1.school_image_container
    = image_tag 'http://thenewrambleon.files.wordpress.com/2011/08/university-of-miami.jpg'
  .span9
    .school_name
      %h4 University of Miami
    = render 'semester', {season: "Fall", year: 2006, courses: @fall_2006}
    = render 'semester', {season: "Spring", year: 2007, courses: @spring_2007}
.grinnell
  .school_image_container
    = image_tag "http://upload.wikimedia.org/wikipedia/en/thumb/e/ea/Honor_'G'.png/220px-Honor_'G'.png"
  .school_name
    %h4 Grinnell College

app/views/static_pages/home.html.haml
- if signed_in?
  .row
    %aside.span4
      %section
        %h1= current_user.name
      %section
        - if @attempts.size >= 10
          %h1 Percent correct
          %h1= number_to_percentage(current_user.answer_percent, :precision => 0)
        - else
          %p
            %strong= "Complete #{10 - @attempts.size} more Questions for stats!"
      %section
        - if @attempts.size > 10
          %section
            %p Last Five Questions
            %ul
            - @attempts.last(5).reverse.each do |a|
              %li= a.vocab_word.name

    .span8
      %h3 Dashboard
      %br
      = link_to "Answer a Question!", new_attempt_path, |
      class: "btn btn-large btn-primary"
      
- else
  .center.hero-unit
    %h1 Welcome to Vocabulator
    %h2
      Master the 500 most common SAT words on the Cloud!
    = link_to "Sign up now!", signup_path, |
      class: "btn btn-large btn-primary" 

app/views/static_pages/jacob.html.haml
- provide(:title, 'Jacob Dankner')
%h1 About the developer
.span-17
  .span-10
    .view_jacob_image
      = image_tag 'jacob.jpg'
  .span-7.last
    %p
      Jacob Dankner is a Software Engineer and maintains this site in his spare time.