config/routes.rb
Vocabulator::Application.routes.draw do
  resources :users
  resources :attempts,      only: [:new, :create, :destroy]
  resources :sessions,      only: [:new, :create, :destroy]
  root to: 'static_pages#home'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  scope :jacob, as: 'jacob' do
    match '/about',      to: 'static_pages#jacob',       via: 'get'
    match '/coursework', to: 'static_pages#coursework',  via: 'get'
  end

  scope :dungeons_and_dragons, as: 'dungeons_and_dragons' do
    match '/home', to: 'd_and_d#home', via: 'get'
    match '/file', to: 'd_and_d#file', via: 'get'
    match '/dm', to: 'd_and_d#dm', via: 'get'
  end

end

app/views/layouts/_d_and_d_header.html.haml
%header.navbar.navbar-fixed-top.navbar-inverse
  .navbar-inner
    .container
      = link_to "Dungeons and Dragons", dungeons_and_dragons_home_path, id: "logo"
      %nav
        %ul.nav.pull-right
          %li= link_to "Main Site", root_path
          %li= link_to "Files & Images", dungeons_and_dragons_file_path
          %li= link_to "From The DM", dungeons_and_dragons_dm_path
          - if signed_in?
            %li= link_to "Users", users_path
            %li#fat-menu.dropdown
              %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                Account
                %b.caret
              %ul.dropdown-menu
                %li= link_to "Profile", current_user
                %li= link_to "Settings", edit_user_path(current_user)
                %li.divider
                %li
                  = link_to "Sign out", signout_path, method: "delete"
          - else
            %li= link_to "Sign in", signin_path

app/views/layouts/_footer.html.haml
%footer.footer
  %small= 'Vocabulator by Jacob Dankner'
  %nav
    %ul
      %li= link_to "About",   about_path
      %li= link_to "Contact", jacob_about_path

app/views/layouts/_header.html.haml
%header.navbar.navbar-fixed-top.navbar-inverse
  .navbar-inner
    .container
      = link_to "Vocabulator", root_path, id: "logo"
      %nav
        %ul.nav.pull-right
          %li= link_to "Home", root_path
          %li#fat-menu.dropdown
            %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
              About
              %b.caret
            %ul.dropdown-menu
              %li= link_to "How it works", about_path
              %li= link_to "The Developer", jacob_about_path
          - if signed_in?
            %li= link_to "Users", users_path
            %li#fat-menu.dropdown
              %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                Account
                %b.caret
              %ul.dropdown-menu
                %li= link_to "Profile", current_user
                %li= link_to "Settings", edit_user_path(current_user)
                %li.divider
                %li
                  = link_to "Sign out", signout_path, method: "delete"
          - else
            %li= link_to "Sign in", signin_path

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= full_title(yield(:title))
    = stylesheet_link_tag "application", media: "all", |
      "data-turbolinks-track" => true                  |
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
    = render 'layouts/shim'
  %body
    = render 'layouts/header'
    .container
      - flash.each do |key, value|
        %div{:class => "alert alert-#{key}"}= value
      = yield
      = render 'layouts/footer'
      = debug(params) if Rails.env.development?

app/views/layouts/d_and_d.html.haml
!!!
%html
  %head
    %title= full_title(yield(:title))
    = stylesheet_link_tag "application", media: "all", |
      "data-turbolinks-track" => true                  |
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
    = render 'layouts/shim'
  %body
    = render 'layouts/d_and_d_header'
    .container
      - flash.each do |key, value|
        %div{:class => "alert alert-#{key}"}= value
      = yield
      = render 'layouts/footer'
      = debug(params) if Rails.env.development?